SUPABASE_URL = "https://ujglimcygjtvjhxjalvj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqZ2xpbWN5Z2p0dmpoeGphbHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjU2NDQsImV4cCI6MjA3MTkwMTY0NH0.c-XfOETRtHYqNht5KwTzUAdJHJaicPNiWmRbMmdYWh8"
